### PR TITLE
Add travis ci

### PR DESCRIPTION
**Pull request by peter-lazorchak**
This branch incorporates Travis CI and leverages the build to send a coverage report to Code Climate.
- Adds Travis build files and remove (unused) Jenkins/docker files
- Adds a tag to the readme: [Build Status](https://travis-ci.org/Contrast-Security-OSS/DjanGoat)
    - The build will be passing in master as soon as this PR goes through :)
- Adds a Makefile with targets for common local actions - `lint`, `test`, etc.
- Fixes a *lot* of linting errors
- Removes the mysql dependency

Right now, everything works with Python 2. Fixing compatibility issues with Python 3 is a top priority.

### CODE REVIEW

**Comment by peter-lazorchak** [comment]
I was hoping Code Climate would show coverage information for this branch, but I think we have to get it into master first. Once this PR goes through, we should see coverage (and hopefully an increased grade) in Code Climate.

I know that they are at least receiving coverage data, because the option to "set up coverage" has disappeared from the site.

**Comment by SteveFeldman** [comment]
@peter-lazorchak do you know if the Jenkins/Docker files were being used internally or does it not matter since @Contrast-AlexB moved it into screener with a different CI and setup?

**Comment by SteveFeldman** [comment]
@peter-lazorchak can you tidy up the README? It still calls for MySQL, but I didn't see anything about SQLite.

**Comment by Contrast-AlexB** [comment]
> @peter-lazorchak do you know if the Jenkins/Docker files were being used internally or does it not matter since @Contrast-AlexB moved it into screener with a different CI and setup?

Screener is not using the Jenkins/Docker file, not sure if it is used internally elsewhere.

**Comment by lazorchakp** [comment]
@SteveFeldman Good point about the readme, I'll update it.

As for Jenkins (@Contrast-AlexB), I checked with @donniepropst too and it seems like everyone's fairly confident we weren't using those files. I'd like to keep them removed unless you have strong opinions otherwise - if it turns out we need them, it's simple to add them back.

**Comment by peter-lazorchak** [comment]
> @SteveFeldman Good point about the readme, I'll update it.
> 
> As for Jenkins (@Contrast-AlexB), I checked with @donniepropst too and it seems like everyone's fairly confident we weren't using those files. I'd like to keep them removed unless you have strong opinions otherwise - if it turns out we need them, it's simple to add them back.

I'm juggling github accounts for schoolwork :/

**Comment by SteveFeldman** [comment]
@peter-lazorchak feel free to merge it...

**Pull request merged**
